import { createPagesFunctionHandler } from "@remix-run/cloudflare-pages";
import type { ServerBuild, AppLoadContext } from "@remix-run/cloudflare";
import type { AuthCache } from "../load-context";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - the server build file is generated by `remix vite:build`
// eslint-disable-next-line import/no-unresolved
import * as build from "../build/server";

// Type assertion needed due to exactOptionalPropertyTypes incompatibility with Remix types
export const onRequest = createPagesFunctionHandler({
  build: build as unknown as ServerBuild,
  getLoadContext: (context): AppLoadContext => {
    // Create a fresh auth cache for each request.
    // This ensures all loaders in a request share the same auth result,
    // preventing multiple refresh attempts with single-use tokens.
    const authCache: AuthCache = {};
    // Type assertion: Cloudflare Pages context differs from PlatformProxy,
    // but contains compatible env and runtime functionality
    return {
      cloudflare: context as unknown as AppLoadContext["cloudflare"],
      authCache,
    };
  },
});
