// Generated by Wrangler on Mon Jan 12 2026 01:13:48 GMT+0000 (Greenwich Mean Time)
// by running `wrangler types`

export interface Env {
  ALIGNMENT_FEED_BASE_URL: string;
  AUTH_SESSION_SECRET: string;
  AUTH0_DOMAIN: string;
  AUTH0_CLIENT_ID: string;
  AUTH0_CLIENT_SECRET: string; // Required for server-side OAuth
  AUTH0_DEFAULT_REDIRECT_URI: string;
  AUTH0_AUDIENCE: string;
  SENTRY_DSN?: string; // Optional Sentry DSN for error tracking
  MINIMAX_API_KEY: string;
  MINIMAX_MODEL: string;
  CHAT_STORAGE_DRIVER: string; // "d1" or "null"
  CHAT_DB?: D1Database; // Required when CHAT_STORAGE_DRIVER=d1
}
