// Generated by Wrangler on Mon Jan 12 2026 01:13:48 GMT+0000 (Greenwich Mean Time)
// by running `wrangler types`

interface Env {
  ALIGNMENT_FEED_BASE_URL: string;
  AUTH_SESSION_SECRET: string;
  AUTH0_DOMAIN: string;
  AUTH0_CLIENT_ID: string;
  AUTH0_CLIENT_SECRET: string; // Required for server-side OAuth
  AUTH0_DEFAULT_REDIRECT_URI: string;
  AUTH0_AUDIENCE: string;
}
