// Generated by Wrangler by running `wrangler types`

interface Env {
  ALIGNMENT_FEED_BASE_URL: string;
  AUTH0_DOMAIN: string;
  AUTH0_CLIENT_ID: string;
  AUTH0_DEFAULT_REDIRECT_URI: string;
  AUTH0_AUDIENCE: string;
}
